### ISSUE TITLE
What’s math rock?

### ISSUE THREAD

**Issue by Qwertz3475** [SegFault-Verm/Ver#93]
I’m

**Comment by SegFault-Verm** [comment]
Math rock is rock that uses irregular time signatures and not common rhythms and is closely related to jazz fusion

**Comment by rose-tinted-glasses** [comment]
This is wrong. Math rock is a genre of rock that uses forms of jazz and post-rock while maintaining a rock-type structure (with the usage of irregular time signatures and rhythms that may not be so common) and is a outsider genre of the popular genre "jazz fusion", which combines rock and jazz directly.
